version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - export
  post_build:
    commands:
      - echo "completed on `date`"
artifacts:
  files:
    - '**/*'